#+title:      vscode
#+date:       [2023-11-25 Sat 18:10]
#+filetags:   :code:
#+identifier: 20231125T181008

* vscode
** vscode vs vim vs emacs lex fridman inspired
** try out evil mode...
it might be more practical to learn to use it instead of emacs
bindings. when you are in shell or when you are in vscode with vim
plugin or when talking to other programmers and when you are in a
browser with vim extension for example.
** Macro for opening same file in vscode

I use Emacs for writing prose and general computing.

But, with respect to programming, I now use both Emacs and VSCode *at the same time for the same files/projects*. (Although predominantly Emacs).

I have been in Academia for years and I have always used Emacs for writing prose and programming (which has been a hobby on the side).

Some months ago, I started working professionally on a Typescript/Angular project. And my co-workers, of course, use VSCode.

Initially, I kept using Emacs. After a while, seeing the several ide features (go to definition, show documentation, etc.) that my colleagues were using, I decided to give VSCode a serious try and I used it to write Typescript/Angular for a whole month or so.

After that, I tried to see whether I could get similar functionalities in Emacs. I tried both LSP Mode and Eglot. After some fighting, I had a quite usable LSP Mode with the ide features I wanted. Not as polished as VSCode, but totally usable. (Eglot was very nice, but I wanted to try ESLint and it looks like with Eglot, atm, you cannot have multiple LSP servers running for the same buffer.)

Instead of going back to Emacs 100%, I decided to try a hybrid approach, which has been very pleasant so far. I use emacs most of the time, but when I feel that VSCode can offer some additional help I turn to it and then go back to Emacs. To make the process smooth I wrote some lines of elisp that make VSCode open the same file I am currently editing, at the same line and the same column. I have it bound to C-Caps (Actually it's C-Escape, because I have Escape remapped to Caps systemwise). When I want, then, I hit a key, VSCode appears, with the cursor placed exactly where Emacs cursor was, I do what I want to do, save if necessary, and switch back to Emacs. I usually keep VSCode already open in the same project, to allow things to be faster. Here is the elisp:

```
(defun gp/vscode-current-buffer-file-at-point ()
  (interactive)
  (start-process-shell-command "code"
			       nil
			       (concat "code --goto "
				       (buffer-file-name)
				       ":"
				       (number-to-string (1+ (current-line))) ;; +1 who knows why
				       ":"
				       (number-to-string (current-column)))))

(define-key global-map (kbd "C-<escape>") 'gp/vscode-current-buffer-file-at-point)
```

&#x200B;

I would also like to able to open Emacs from VSCode, remaining in the same file, same line and column, too. Does anyone know how to do that?  I couldn't be bothered, so far...

Assuming that Emacs is better than VSCode at certain things (say, text-editing, keyboard-macros, extensibility on the fly) and VSCode is better than Emacs (at least, non-relevantly extended Emacs) at other things (say, code navigation/visualization and certain code-completions), using both at the same time is, I think, an approach that deserves some thought.
** vscode shortcuts
- ~c-k c-t~ - choose theme
- syncing to other devices with github login in vs code...
- ~c-shift-p~ - ope command pallet
- ~f5~ - run and debug ANY file
- jupyter notebooks in vscode? what is it for
- ~c-k c-o~ - open a folder(opens up nautilus)
- ~shift+alt+click/up/down~ multiple cursors
- ~ctrl+shift+k~ - delete entire line
- ~f2~ - rename variable
- ~c+shift+i~ - format entire document
- ~c+k c+f~ - format selection
- ~c+shift+[]~ - fold unfold code
- type "if" or "try" and then select some sugeested completion snippet..
- emmet works just the same
- ~c-`~ open terminal
- ~c-,~ - open settings
- ~C-1, C-2, C-3~ - different windows
- file->autosave - autosaves every little change
- ~c-n~ - create new file
- live server/live preview - html/css editing on the fly
- ~c+shift+g~ git interface
- run auto detected tasks(google when its useful)
- ~c+k c+s~ customize shortcuts
- eslint extensions for smth many downloads
** vscode plugins
** VScode github real life examples
plugin name - IntelliCode API Usage Examples
** https://desktop.github.com/
** why vscode

ar mane stabdo emacs?

pycharm is like an 18 wheeler truck and emacs is like your comfortable
toyota - Guido

Vscode is great. Its like a home i can go back to when I'm lost. But
Emacs is an adventure - Guy on youtube

[[https://www.youtube.com/watch?v=G5mtQhWNezQ&ab_channel=LexClips][sita kalba lex su Guido]]

- lex (vscode now 20k hours emacs)
- python create Guide Van Rossum (VSCODE now, 30 years emacs)
- George hotz(vscode + vim)
** Trying out other editors

I think it really depends on what someone wants out of Emacs. The
thread the other day on people who use both had a pretty strong choir
of people who use Org-mode for note taking and VS Code for dev work,
which makes perfect sense to me; Emacs guaranteed itself a place in my
workflow with Org-mode.

I think if you're satisfied with Emacs for now and you can concretely
point to packages and functionality in Emacs that you would not know
how to recreate in VS Code out of the gate, I would say there's not a
ton of reason to switch to VS Code. I'm largely in the same boat, know
the basics of some front-end web-dev, occasionally play around with CL
and elisp, all non-professionally.

Compatibility with a hypothetical future team will be dependent on
that team, and at the same time many of the guides/tutorials for Emacs
I've read encourage learning other editors and how they work in case
you run into an employment situation that won't work with Emacs for
whatever reason. Seems like good practice.
** Reason

I think people overvalue this kind of thing. Vscode is going to be
around for quite a while. If you think it would improve your life, you
should use it. It might eventually go away in 15 years, but if it
does, you can spend a weekend switching to something else. That’s
hardly a reason to use a suboptimal tool until then. Of course, you
may prefer Emacs, and that’s fine too. Just saying, I think it’s
unwise to avoid an extremely healthy ecosystem and tool purely on the
grounds that it might not exist forever.
** Andrei karpathy emacs lex did it convince him
** automatic formatting with prettier
https://youtube.com/shorts/dDtueNAFELo?si=EDK6Ospk9N38QY_L
